### PR TITLE
Created homepage

### PR DESCRIPTION
**Pull request by erincuenco**

### CODE REVIEW

**Review by rbaguila — COMMENTED** [review]
Take note that the images must not be stored in the project's directory. Please search about cloudinary image or s3 buckets in the future.

**Comment by rbaguila** [comment]
Also, why do the changes with the 2nd PR appears in your current PR? For example: the scripts directory.

**Comment by rbaguila** [comment]
You must point your base branch to `develop` instead of `master`

**Review by rbaguila — COMMENTED** [review]
Please attach a screenshot of the homepage in the comments section. :)

**Comment by erincuenco** [comment]
Thanks for the review! Attached is the screenshot of the homepage.
1homepage

**Comment by rbaguila** [comment]
Looks good! PR Approved! 👍

**Review by rbaguila — APPROVED** [review]

**Pull request merged**
